### ISSUE TITLE
add support to import archives

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain-docker#100]
Hiro provides archives for the chain states.
It would be nice if there are instructions or commands how to import or use an archive.

Currently, the persistent-data folder has root permissions and it is not straight forward to import both the chain state and the postgres archive.

**Comment by wileyj** [comment]
100% agree. I've already been speaking to them about utilizing this before
i just do it 😄

**Comment by rafaelcr** [comment]
+1 I was just going to create this issue, would be super useful!
It would also be a good time to upgrade to Postgres 15 @wileyj given that the latest archives we have are for pg15 👍

**Comment by wileyj** [comment]
> +1 I was just going to create this issue, would be super useful! It would also be a good time to upgrade to Postgres 15 @wileyj given that the latest archives we have are for pg15 👍

https://github.com/stacks-network/stacks-blockchain-docker/pull/104

i have to document how to use it, but the gist is:
1. clone repo
2. `sudo ./scripts/seed-chainstate.sh`
3. wait a **really** long time (didn't time my tests, but around 60 minutes is what i recall the entire process taking)
4. start the services normally

the next stage now that the script is working reasonably well is to add a flag to do this on first startup, i.e. `./manage.sh -n mainnet -a seed` or something like that, but that'll take some time to figure out.

**Comment by wileyj** [comment]
there are 2 places in the script that require user input, the first to delete any existing data, and the second to start the download process. simple "y" keystroke at the prompt

**Comment by friedger** [comment]
Nice

**Comment by friedger** [comment]
After running through the flow I now receive a missing parent error. Do I need to do it again? Is something else I can do? @wileyj 

stacks-blockchain-api  | {"level":"error","message":"error processing core-node /new_block: Error: DB does not contain a parent block at height 98596 with index_hash 0x37fafb8b53639d59be2873586aeceb0847bff50c623365528fe062267149adcb DB does not contain a parent block at height 98596 with index_hash 0x37fafb8b53639d59be2873586aeceb0847bff50c623365528fe062267149adcb","stack":"Error: DB does not contain a parent block at height 98596 with index_hash 0x37fafb8b53639d59be2873586aeceb0847bff50c623365528fe062267149adcb\n    at PgWriteStore.handleReorg (/app/src/datastore/pg-write-store.ts:2655:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /app/src/datastore/pg-write-store.ts:223:7\n    at scope (/app/node_modules/postgres/cjs/src/index.js:222:18)\n    at Function.begin (/app/node_modules/postgres/cjs/src/index.js:209:14)\n    at PgWriteStore.update (/app/src/datastore/pg-write-store.ts:221:5)\n    at handleBlockMessage (/app/src/event-stream/event-server.ts:320:3)\n    at run (/app/node_modules/p-queue/dist/index.js:163:29)","timestamp":"2023-03-30T12:32:14.866Z"}

**Comment by wileyj** [comment]
something is definitely off, the block height in your log message should be
higher. if you can run it again but save the output this time that would be
helpful. if you don't want to share here you can email it to me.

i think I'll adjust the process a bit as well today

**Comment by pleaseshutup** [comment]
@wileyj i see you added updates to seed-chainstate.sh as you said you would.
If all good would you mind adding to the README? I didn't even know this option was available until i was lucky to catch a comment on it on the stacks discord.

**Comment by wileyj** [comment]
simple reason: the script isn't fully ready, but will be documented. it
*should* work now but needs more dry and better error handling.

**Comment by pleaseshutup** [comment]
OK FWIW
I recently upgrade a node to 2.1
Waited 3 days to see if I could get it to re-sync but i only got to block ~47000 before I figured F-it i'll try this script.

It ran successfully just now, and my node is at 100498 and catching up. Should be fully caught up soon!

Thanks :-)

**Comment by wileyj** [comment]
nice, glad to hear it! i will get to the docs soon but appreciate the
feedback

**Comment by wileyj** [comment]
@pleaseshutup @friedger 
added some documentation here after simplifying the script a bit, but note that now `sudo` is required (if you run as a normal user, it will error out that you need to run with sudo). 
still need to lint it and possibly add an option to run it as part of `start` but it's getting close to being done. 

https://github.com/stacks-network/stacks-blockchain-docker/pull/106

**Comment by pleaseshutup** [comment]
@wileyj looks great to me!

**Comment by wileyj** [comment]
> @wileyj looks great to me!

excellent! i'll keep this issue open since there's still some additional logic i'd like to add.

**Comment by s4ndxyz** [comment]
I clone this repo and then run `sudo ./scripts/seed-chainstate.sh`.
When it finished I run `./manage.sh -n mainnet -a start`
But shows errors, what should I do?
`stacks-blockchain      | ERRO [1681789545.660332] [testnet/stacks-node/src/event_dispatcher.rs:142] [chains-coordinator-0.0.0.0:20443] Event dispatcher: Failed POST, url: http://stacks-blockchain-api:3700/new_block, err: Response { status: InternalServerError, headers: {"keep-alive": "timeout=5", "date": "Tue, 18 Apr 2023 03:45:45 GMT", "content-type": "application/json; charset=utf-8", "x-powered-by": "Express", "etag": "W/\"c-3Rk1bge0s6VuJbi+S2m2iU0UGdY\"", "connection": "keep-alive", "content-length": "12"}, version: None, has_trailers: false, trailers_sender: Some(Sender { .. }), trailers_receiver: Some(Receiver { .. }), upgrade_sender: Some(Sender { .. }), upgrade_receiver: Some(Receiver { .. }), has_upgrade: false, body: Body { reader: "<hidden>", length: Some(12), bytes_read: 0 }, ext: Extensions, local_addr: None, peer_addr: None }
stacks-blockchain-api  | {"level":"error","message":"HTTP POST /new_block","req":{"headers":{"content-length":"109225","content-type":"application/json","host":"stacks-blockchain-api:3700"},"httpVersion":"1.1","method":"POST","originalUrl":"/new_block","query":{},"url":"/new_block"},"res":{"statusCode":500},"responseTime":9,"timestamp":"2023-04-18T03:45:45.660Z"}
`

**Comment by wileyj** [comment]
@s4ndxyz can you open a new issue for this? this sounds like more an API issue i want to clarify, but don't want to spam here.
