### ISSUE TITLE
Add Explorer as an option for all network options

### ISSUE THREAD

**Issue by ceramicwhite** [stacks-network/stacks-blockchain-docker#61]
Add an `explorer` flag for all `<network>` options.

These env variables should be configure to their respective `local:3999` :
`NEXT_PUBLIC_MAINNET_API_SERVER`
`NEXT_PUBLIC_TESTNET_API_SERVER`

If using the `proxy` flag, expose the explorer at a subdomain and potentially allow configuration throw a variable added to .env, such as:
`EXPLORER_SUBDOMAIN=explorer.${VIRTUAL_HOST}`
`API_SUBDOMAIN=stacks-api.${VIRTUAL_HOST}`

**Comment by wileyj** [comment]
This idea was pretty contentious in the past when it was part of the stack here. 

I've been reworking how the flags work in https://github.com/stacks-network/stacks-blockchain-docker/tree/feat/option-parsing
Once that work is done and merged, it might be easier to accomplish what you're suggesting without causing issues.

**Comment by criadoperez** [comment]
Could be interesting to add. Let me know if you need a hand doing so.
