### ISSUE TITLE
manage.sh does not launch in linux enviroment

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain-docker#66]
The env command is expected as `/bin/env`, however, on linux it is usually at `/usr/bin/env`

**Comment by wileyj** [comment]
Which dist are you using? for Debian, both paths are accurate

**Comment by friedger** [comment]
@wileyj ubuntu

**Comment by wileyj** [comment]
I'll have to try this myself - i've only ever used non-ubuntu versions of linux. 
what release version of ubuntu did you notice this on?

**Comment by wileyj** [comment]
Best that i can tell is that either `/bin/env` *or* `/usr/bin/env` is a hardlink, where `/bin/env` isn't present on some ubuntu releases for whatever reason. 
https://github.com/stacks-network/stacks-blockchain-docker/commit/449c4e5784c3bd82e548fed514f16029f7dbe72d

to quote my commit: "thanks mark"
